stages:
  - docker
  - test
  - validate
  - plan
  - apply

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${CI_PROJECT_DIR}/services/talk_booking/.venv/

build-python-ci-image:
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  stage: docker
  before_script:
    - cd ci_cd/python/
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t registry.gitlab.com/carltonlnd/talk-booking:cicd-python3.10-slim .
    - docker push registry.gitlab.com/carltonlnd/talk-booking:cicd-python3.10-slim
  only:
    refs:
      - main
    changes:
      - ci_cd/python/Dockerfile

include:
  - local: /infrastructure/global/vpc/ci-cd.yml
  - local: /services/talk_booking/ci-cd.yml
